#!/usr/bin/env tclsh

###
# Copyright 2013 Matthew Harvey
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

# Copy text of LICENSE into "user_guide" directory, with suitable title and
# file extension to satisfy Sphinx.
set in [open "LICENSE" r]
set out [open [file nativename "user_guide/LICENSE.rst"] w]
puts $out "LICENSE"
puts $out "======="
puts $out ""
while {[gets $in line] >= 0} {
    puts $out $line
}
close $in
flush $out
close $out

# Generate html user guide using Sphinx
exec sphinx-build -b html -d [file nativename "user_guide/_build/doctrees"] \
    user_guide [file nativename "user_guide/_build/html"] \
    2>@ stderr >@stdout

# Generate additional files containing license and author details for third
# party components included in the files generated by Sphinx.
set static_dir "user_guide/_build/html/_static"
set files_in_static_dir [glob -types f -directory $static_dir *]
file mkdir "${static_dir}/license_dir"
file mkdir "${static_dir}/authors_dir"
set license_dict [ \
    dict create \
        ajax-loader.gif       sphinx-basic-theme \
        basic.css             sphinx-basic-theme \
        better.css          { better-theme-license  ""             } \
        better-basic.css    { better-theme-license  ""             } \
        comment-bright.png    sphinx-basic-theme \
        comment-close.png     sphinx-basic-theme \
        comment.png           sphinx-basic-theme \
        doctools.js         { sphinx-license        sphinx-authors } \
        down-pressed.png      sphinx-basic-theme \
        down.png              sphinx-basic-theme \
        file.png              sphinx-basic-theme \
        icon_100_100.png    { dcm-images-license    dcm-images-authors } \
        jquery.js             sphinx-third-party \
        minus.png             sphinx-basic-theme \
        plus.png              sphinx-basic-theme \
        pygments.css          sphinx-generated \
        searchtools.js      { sphinx-license       sphinx-authors } \
        underscore.js         sphinx-third-party \
        up-pressed.png        sphinx-basic-theme \
        up.png                sphinx-basic-theme \
        websupport.js       { sphinx-license       sphinx-authors } \
]






