# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matthew/Workbench/phatbooks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matthew/Workbench/phatbooks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthew/Workbench/phatbooks/CMakeFiles /home/matthew/Workbench/phatbooks/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthew/Workbench/phatbooks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

account.o: account.cpp.o
.PHONY : account.o

# target to build an object file
account.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/account.cpp.o
.PHONY : account.cpp.o

account.i: account.cpp.i
.PHONY : account.i

# target to preprocess a source file
account.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/account.cpp.i
.PHONY : account.cpp.i

account.s: account.cpp.s
.PHONY : account.s

# target to generate assembly for a file
account.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/account.cpp.s
.PHONY : account.cpp.s

application.o: application.cpp.o
.PHONY : application.o

# target to build an object file
application.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/application.cpp.o
.PHONY : application.cpp.o

application.i: application.cpp.i
.PHONY : application.i

# target to preprocess a source file
application.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/application.cpp.i
.PHONY : application.cpp.i

application.s: application.cpp.s
.PHONY : application.s

# target to generate assembly for a file
application.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/application.cpp.s
.PHONY : application.cpp.s

database.o: database.cpp.o
.PHONY : database.o

# target to build an object file
database.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/database.cpp.o
.PHONY : database.cpp.o

database.i: database.cpp.i
.PHONY : database.i

# target to preprocess a source file
database.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/database.cpp.i
.PHONY : database.cpp.i

database.s: database.cpp.s
.PHONY : database.s

# target to generate assembly for a file
database.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/database.cpp.s
.PHONY : database.cpp.s

identifier.o: identifier.cpp.o
.PHONY : identifier.o

# target to build an object file
identifier.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/identifier.cpp.o
.PHONY : identifier.cpp.o

identifier.i: identifier.cpp.i
.PHONY : identifier.i

# target to preprocess a source file
identifier.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/identifier.cpp.i
.PHONY : identifier.cpp.i

identifier.s: identifier.cpp.s
.PHONY : identifier.s

# target to generate assembly for a file
identifier.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/identifier.cpp.s
.PHONY : identifier.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

stored_object.o: stored_object.cpp.o
.PHONY : stored_object.o

# target to build an object file
stored_object.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stored_object.cpp.o
.PHONY : stored_object.cpp.o

stored_object.i: stored_object.cpp.i
.PHONY : stored_object.i

# target to preprocess a source file
stored_object.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stored_object.cpp.i
.PHONY : stored_object.cpp.i

stored_object.s: stored_object.cpp.s
.PHONY : stored_object.s

# target to generate assembly for a file
stored_object.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stored_object.cpp.s
.PHONY : stored_object.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... account.o"
	@echo "... account.i"
	@echo "... account.s"
	@echo "... application.o"
	@echo "... application.i"
	@echo "... application.s"
	@echo "... database.o"
	@echo "... database.i"
	@echo "... database.s"
	@echo "... identifier.o"
	@echo "... identifier.i"
	@echo "... identifier.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stored_object.o"
	@echo "... stored_object.i"
	@echo "... stored_object.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

