		vec.push_back(make_currency(dbc, L"Kazakhstani tenge", "KZT", 2));
		vec.push_back(make_currency(dbc, L"Chilean peso", "CLP", 2));
		vec.push_back(make_currency(dbc, L"Central African CFA franc", "XAF", 2));
		vec.push_back(make_currency(dbc, L"Afghan afghani", "AFN", 2));
		vec.push_back(make_currency(dbc, L"Belize dollar", "BZD", 2));
		vec.push_back(make_currency(dbc, L"Albanian lek", "ALL", 2));
		vec.push_back(make_currency(dbc, L"Algerian dinar", "DZD", 2));
		vec.push_back(make_currency(dbc, L"Croatian kuna", "HRK", 2));
		vec.push_back(make_currency(dbc, L"Angolan kwanza", "AOA", 2));
		vec.push_back(make_currency(dbc, L"Argentine peso", "ARS", 2));
		vec.push_back(make_currency(dbc, L"Armenian dram", "AMD", 2));
		vec.push_back(make_currency(dbc, L"Aruban florin", "AWG", 2));
		vec.push_back(make_currency(dbc, L"Australian dollar", "AUD", 2));
		vec.push_back(make_currency(dbc, L"Azerbaijani manat", "AZN", 2));
		vec.push_back(make_currency(dbc, L"Bahamian dollar", "BSD", 2));
		vec.push_back(make_currency(dbc, L"Bahraini dinar", "BHD", 3));
		vec.push_back(make_currency(dbc, L"Bangladeshi taka", "BDT", 2));
		vec.push_back(make_currency(dbc, L"Barbadian dollar", "BBD", 2));
		vec.push_back(make_currency(dbc, L"Belarusian ruble", "BYR", 2));
		vec.push_back(make_currency(dbc, L"Bermudian dollar", "BMD", 2));
		vec.push_back(make_currency(dbc, L"Bhutanese ngultrum", "BTN", 2));
		vec.push_back(make_currency(dbc, L"Bolivian boliviano", "BOB", 2));
		vec.push_back(make_currency(dbc, L"Bosnia and Herzegovina convertible mark", "BAM", 2));
		vec.push_back(make_currency(dbc, L"Botswana pula", "BWP", 2));
		vec.push_back(make_currency(dbc, L"Brazilian real", "BRL", 2));
		vec.push_back(make_currency(dbc, L"British pound", "GBP", 2));
		vec.push_back(make_currency(dbc, L"Brunei dollar", "BND", 2));
		vec.push_back(make_currency(dbc, L"Bulgarian lev", "BGN", 2));
		vec.push_back(make_currency(dbc, L"Burmese kyat", "MMK", 2));
		vec.push_back(make_currency(dbc, L"Burundian franc", "BIF", 2));
		vec.push_back(make_currency(dbc, L"Cambodian riel", "KHR", 2));
		vec.push_back(make_currency(dbc, L"Canadian dollar", "CAD", 2));
		vec.push_back(make_currency(dbc, L"Cape Verdean escudo", "CVE", 2));
		vec.push_back(make_currency(dbc, L"Cayman Islands dollar", "KYD", 2));
		vec.push_back(make_currency(dbc, L"CFP franc", "XPF", 2));
		vec.push_back(make_currency(dbc, L"Chinese yuan", "CNY", 2));
		vec.push_back(make_currency(dbc, L"Colombian peso", "COP", 2));
		vec.push_back(make_currency(dbc, L"Comorian franc", "KMF", 2));
		vec.push_back(make_currency(dbc, L"Congolese franc", "CDF", 2));
		vec.push_back(make_currency(dbc, L"Costa Rican colón", "CRC", 2));
		vec.push_back(make_currency(dbc, L"Cuban convertible peso", "CUC", 2));
		vec.push_back(make_currency(dbc, L"Cuban peso", "CUP", 2));
		vec.push_back(make_currency(dbc, L"Czech koruna", "CZK", 2));
		vec.push_back(make_currency(dbc, L"Danish krone", "DKK", 2));
		vec.push_back(make_currency(dbc, L"Djiboutian franc", "DJF", 2));
		vec.push_back(make_currency(dbc, L"Dominican peso", "DOP", 2));
		vec.push_back(make_currency(dbc, L"East Caribbean dollar", "XCD", 2));
		vec.push_back(make_currency(dbc, L"Egyptian pound", "EGP", 2));
		vec.push_back(make_currency(dbc, L"Eritrean nakfa", "ERN", 2));
		vec.push_back(make_currency(dbc, L"Ethiopian birr", "ETB", 2));
		vec.push_back(make_currency(dbc, L"Euro", "EUR", 2));
		vec.push_back(make_currency(dbc, L"Falkland Islands pound", "FKP", 2));
		vec.push_back(make_currency(dbc, L"Fijian dollar", "FJD", 2));
		vec.push_back(make_currency(dbc, L"Gambian dalasi", "GMD", 2));
		vec.push_back(make_currency(dbc, L"Georgian lari", "GEL", 2));
		vec.push_back(make_currency(dbc, L"Ghana cedi", "GHS", 2));
		vec.push_back(make_currency(dbc, L"Gibraltar pound", "GIP", 2));
		vec.push_back(make_currency(dbc, L"Guatemalan quetzal", "GTQ", 2));
		vec.push_back(make_currency(dbc, L"Guernsey pound", "GGP", 2));
		vec.push_back(make_currency(dbc, L"Guinean franc", "GNF", 2));
		vec.push_back(make_currency(dbc, L"Guyanese dollar", "GYD", 2));
		vec.push_back(make_currency(dbc, L"Haitian gourde", "HTG", 2));
		vec.push_back(make_currency(dbc, L"Honduran lempira", "HNL", 2));
		vec.push_back(make_currency(dbc, L"Hong Kong dollar", "HKD", 2));
		vec.push_back(make_currency(dbc, L"Hungarian forint", "HUF", 2));
		vec.push_back(make_currency(dbc, L"Icelandic króna", "ISK", 2));
		vec.push_back(make_currency(dbc, L"Indian rupee", "INR", 2));
		vec.push_back(make_currency(dbc, L"Indonesian rupiah", "IDR", 2));
		vec.push_back(make_currency(dbc, L"Iranian rial", "IRR", 2));
		vec.push_back(make_currency(dbc, L"Iraqi dinar", "IQD", 3));
		vec.push_back(make_currency(dbc, L"Israeli new shekel", "ILS", 2));
		vec.push_back(make_currency(dbc, L"Jamaican dollar", "JMD", 2));
		vec.push_back(make_currency(dbc, L"Japanese yen", "JPY", 2));
		vec.push_back(make_currency(dbc, L"Jersey pound", "JEP", 2));
		vec.push_back(make_currency(dbc, L"Jordanian dinar", "JOD", 2));
		vec.push_back(make_currency(dbc, L"Kenyan shilling", "KES", 2));
		vec.push_back(make_currency(dbc, L"Kuwaiti dinar", "KWD", 3));
		vec.push_back(make_currency(dbc, L"Kyrgyzstani som", "KGS", 2));
		vec.push_back(make_currency(dbc, L"Lao kip", "LAK", 2));
		vec.push_back(make_currency(dbc, L"Latvian lats", "LVL", 2));
		vec.push_back(make_currency(dbc, L"Lebanese pound", "LBP", 2));
		vec.push_back(make_currency(dbc, L"Lesotho loti", "LSL", 2));
		vec.push_back(make_currency(dbc, L"Liberian dollar", "LRD", 2));
		vec.push_back(make_currency(dbc, L"Libyan dinar", "LYD", 3));
		vec.push_back(make_currency(dbc, L"Lithuanian litas", "LTL", 2));
		vec.push_back(make_currency(dbc, L"Macanese pataca", "MOP", 2));
		vec.push_back(make_currency(dbc, L"Macedonian denar", "MKD", 2));
		vec.push_back(make_currency(dbc, L"Malawian kwacha", "MWK", 2));
		vec.push_back(make_currency(dbc, L"Malaysian ringgit", "MYR", 2));
		vec.push_back(make_currency(dbc, L"Maldivian rufiyaa", "MVR", 2));
		vec.push_back(make_currency(dbc, L"Manx pound", "IMP", 2));
		vec.push_back(make_currency(dbc, L"Mauritian rupee", "MUR", 2));
		vec.push_back(make_currency(dbc, L"Mexican peso", "MXN", 2));
		vec.push_back(make_currency(dbc, L"Moldovan leu", "MDL", 2));
		vec.push_back(make_currency(dbc, L"Mongolian tögrög", "MNT", 2));
		vec.push_back(make_currency(dbc, L"Moroccan dirham", "MAD", 2));
		vec.push_back(make_currency(dbc, L"Mozambican metical", "MZN", 2));
		vec.push_back(make_currency(dbc, L"Namibian dollar", "NAD", 2));
		vec.push_back(make_currency(dbc, L"Nepalese rupee", "NPR", 2));
		vec.push_back(make_currency(dbc, L"Netherlands Antillean guilder", "ANG", 2));
		vec.push_back(make_currency(dbc, L"New Taiwan dollar", "TWD", 2));
		vec.push_back(make_currency(dbc, L"New Zealand dollar", "NZD", 2));
		vec.push_back(make_currency(dbc, L"Nicaraguan córdoba", "NIO", 2));
		vec.push_back(make_currency(dbc, L"Nigerian naira", "NGN", 2));
		vec.push_back(make_currency(dbc, L"North Korean won", "KPW", 2));
		vec.push_back(make_currency(dbc, L"Norwegian krone", "NOK", 2));
		vec.push_back(make_currency(dbc, L"Omani rial", "OMR", 3));
		vec.push_back(make_currency(dbc, L"Pakistani rupee", "PKR", 2));
		vec.push_back(make_currency(dbc, L"Panamanian balboa", "PAB", 2));
		vec.push_back(make_currency(dbc, L"Papua New Guinean kina", "PGK", 2));
		vec.push_back(make_currency(dbc, L"Paraguayan guaraní", "PYG", 2));
		vec.push_back(make_currency(dbc, L"Peruvian nuevo sol", "PEN", 2));
		vec.push_back(make_currency(dbc, L"Philippine peso", "PHP", 2));
		vec.push_back(make_currency(dbc, L"Polish złoty", "PLN", 2));
		vec.push_back(make_currency(dbc, L"Qatari riyal", "QAR", 2));
		vec.push_back(make_currency(dbc, L"Romanian leu", "RON", 2));
		vec.push_back(make_currency(dbc, L"Russian ruble", "RUB", 2));
		vec.push_back(make_currency(dbc, L"Rwandan franc", "RWF", 2));
		vec.push_back(make_currency(dbc, L"Saint Helena pound", "SHP", 2));
		vec.push_back(make_currency(dbc, L"Salvadoran colón", "SVC", 2));
		vec.push_back(make_currency(dbc, L"Samoan tālā", "WST", 2));
		vec.push_back(make_currency(dbc, L"São Tomé and Príncipe dobra", "STD", 2));
		vec.push_back(make_currency(dbc, L"Saudi riyal", "SAR", 2));
		vec.push_back(make_currency(dbc, L"Serbian dinar", "RSD", 2));
		vec.push_back(make_currency(dbc, L"Seychellois rupee", "SCR", 2));
		vec.push_back(make_currency(dbc, L"Sierra Leonean leone", "SLL", 2));
		vec.push_back(make_currency(dbc, L"Singapore dollar", "SGD", 2));
		vec.push_back(make_currency(dbc, L"Solomon Islands dollar", "SBD", 2));
		vec.push_back(make_currency(dbc, L"Somali shilling", "SOS", 2));
		vec.push_back(make_currency(dbc, L"South African rand", "ZAR", 2));
		vec.push_back(make_currency(dbc, L"South Korean won", "KRW", 2));
		vec.push_back(make_currency(dbc, L"South Sudanese pound", "SSP", 2));
		vec.push_back(make_currency(dbc, L"Sri Lankan rupee", "LKR", 2));
		vec.push_back(make_currency(dbc, L"Sudanese pound", "SDG", 2));
		vec.push_back(make_currency(dbc, L"Surinamese dollar", "SRD", 2));
		vec.push_back(make_currency(dbc, L"Swazi lilangeni", "SZL", 2));
		vec.push_back(make_currency(dbc, L"Swedish krona", "SEK", 2));
		vec.push_back(make_currency(dbc, L"Swiss franc", "CHF", 2));
		vec.push_back(make_currency(dbc, L"Syrian pound", "SYP", 2));
		vec.push_back(make_currency(dbc, L"Tajikistani somoni", "TJS", 2));
		vec.push_back(make_currency(dbc, L"Tanzanian shilling", "TZS", 2));
		vec.push_back(make_currency(dbc, L"Thai baht", "THB", 2));
		vec.push_back(make_currency(dbc, L"Tongan paʻanga", "TOP", 2));
		vec.push_back(make_currency(dbc, L"Transnistrian ruble", "PRB", 2));
		vec.push_back(make_currency(dbc, L"Trinidad and Tobago dollar", "TTD", 2));
		vec.push_back(make_currency(dbc, L"Tunisian dinar", "TND", 3));
		vec.push_back(make_currency(dbc, L"Turkish lira", "TRY", 2));
		vec.push_back(make_currency(dbc, L"Turkmenistan manat", "TMT", 2));
		vec.push_back(make_currency(dbc, L"Ugandan shilling", "UGX", 2));
		vec.push_back(make_currency(dbc, L"Ukrainian hryvnia", "UAH", 2));
		vec.push_back(make_currency(dbc, L"United Arab Emirates dirham", "AED", 2));
		vec.push_back(make_currency(dbc, L"United States dollar", "USD", 2));
		vec.push_back(make_currency(dbc, L"Uruguayan peso", "UYU", 2));
		vec.push_back(make_currency(dbc, L"Uzbekistani som", "UZS", 2));
		vec.push_back(make_currency(dbc, L"Vanuatu vatu", "VUV", 0));
		vec.push_back(make_currency(dbc, L"Venezuelan bolívar", "VEF", 2));
		vec.push_back(make_currency(dbc, L"Vietnamese đồng", "VND", 1));
		vec.push_back(make_currency(dbc, L"West African CFA franc", "XOF", 2));
		vec.push_back(make_currency(dbc, L"Yemeni rial", "YER", 2));
		vec.push_back(make_currency(dbc, L"Zambian kwacha", "ZMW", 2));
